name: artifacts

on:
  push:
    branches: [ master ]
    tags: ['*']
    paths-ignore: ['**.md']
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  VCPKG_ROOT: C:\vcpkg
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

jobs:
  msvc:
    if: ${{ github.repository == 'fabiangreffrath/woof' }}
    runs-on: windows-latest

    strategy:
      matrix:
        conf:
          - platform: Win32
            arch: x86
          - platform: x64
            arch: x64

    steps:
      - uses: actions/checkout@v3

      - name: Setup vcpkg and NuGet
        shell: bash
        run: |
          set -euo pipefail
          cd ${{ env.VCPKG_ROOT }}
          git pull
          ./bootstrap-vcpkg.sh -disableMetrics
          nuget=$(./vcpkg.exe fetch nuget | tail -n 1)
          owner="${GITHUB_REPOSITORY%/*}"
          source_url="https://nuget.pkg.github.com/$owner/index.json"
          "$nuget" sources add \
            -source "$source_url" \
            -storepasswordincleartext \
            -name "GitHub" \
            -username "$owner" \
            -password "${{ secrets.GITHUB_TOKEN }}"
          "$nuget" setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -source "$source_url"

      - name: Configure
        run: |
          cmake -B build -A ${{ matrix.conf.platform }} `
            -DCMAKE_BUILD_TYPE=Release -DENABLE_WERROR=ON `
            -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET="${{ matrix.conf.arch }}-windows-static-release" `
            -DVCPKG_OVERLAY_TRIPLETS="cmake/triplets"

      - name: Build
        shell: bash
        run: |
          cmake --build build -- -maxcpucount -verbosity:minimal

      - name: Package
        run: |
          cd build
          cpack -G ZIP

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Win-${{ matrix.conf.arch }}
          path: build/*.zip

      - name: Extract Version Number
        shell: bash
        run: echo "VERSION=${GITHUB_REF##*_}" >> $GITHUB_ENV

      - name: Release
        if: ${{ contains(github.ref, 'tags') }}
        uses: ncipollo/release-action@v1
        with:
          name: Woof! ${{ env.VERSION }}
          bodyFile: CHANGELOG.md
          allowUpdates: true
          artifacts: build/*.zip
